### ISSUE TITLE
A question on manifold projection for StyleGAN

### ISSUE THREAD

**Issue by aiueogawa** [quolc/neural-collage#9]
Thank you for greate paper!

I have a question about a manifold projection method for StyleGAN generator.
Did you use the same way where the loss function is described in Equation (4) in paper to obtain the corresponding latent/style representation of a given image?

Thanks in advance!

**Comment by aiueogawa** [comment]
@quolc 
Sorry, I forgot mentioning.

**Comment by quolc** [comment]
Hi.
For StyleGAN, we used the VGG model for calculating the perceptual loss.
Though we haven't released the codes for other than the SNGAN model in this repository,
you can use another TF implementation by Puzer for this purpose.
https://github.com/Puzer/stylegan-encoder

**Comment by aiueogawa** [comment]
@quolc
Thank you for your reply.
Puzer uses a style representation instead of an entangled latent one but which did you use?
And how about requirement of an encoder and fast manifold projection techniques?

**Comment by quolc** [comment]
@aiueogawa 
In our study, we used style representation W instead of the entangled latent Z.
Please note that all the StyleGAN results shown in our preprint are the products of feature collage, i.e. direct mixing of intermediate feature tensors from different Z.
Of course, the spatial mixing of style variable W would give interesting results.

Since StyleGAN has a good disentangled leaned representation, I think you can obtain satisfactory projection results w/o encoder and fast projection techniques.
FYI: optimizing noise matrices in addition to W gives better reconstruction quality.

**Comment by aiueogawa** [comment]
＠quolc
All things were clarified well.
Thanks for all!
